version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: staffy
      POSTGRES_PASSWORD: staffypass
      POSTGRES_DB: staffy
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data

  bot:
    build: .
    volumes:
      - ./bot-data:/app/data
    restart: always
    depends_on:
      - db
      - redis

volumes:
  db-data:
  redis_data:
  bot-data:
